spring:
    application:
        name: ace-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
server:
    port: 8765 #启动端口

zuul:
  #prefix: /techouse #为zuul设置一个公共的前缀
  #ignoredServices: '*'
  routes:
    rule-ui: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
      path: /rule/ui/** #匹配/techouse/usersystem/** 均路由到cloud-client
    rule-service:
      path: /rule/service/**

ribbon:
  eureka:
    enabled: false #配置zuul路由时用将此属性设置为false

rule-ui:
  ribbon:
    listOfServers: 127.0.0.1:8766 #为cloud-client服务指定一组服务地址，应该是用于负载均衡
rule-service:
  ribbon:
    listOfServers: 127.0.0.1:8762

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
security:
    user:
        name: admin
        password: admin
        role: USER