-- 删除表
DROP TABLE RISK_MODEL_SENCE;
DROP TABLE RISK_MODEL_RELEASE;
DROP TABLE RISK_VALIDATE_BATCH;
DROP TABLE RISK_VARIABLE_BIND;
DROP TABLE RISK_RULE_HIS_VERSION;

DROP TABLE RISK_MODEL_LOG;
DROP TABLE RISK_DROOLS_LOG;
DROP TABLE RISK_DROOLS_DETAIL_LOG;
DROP TABLE TABLERISK_MODELVALIDATE_LOG;





-- 创建表
-- 1 模型与策略关系表，记录模型关联了哪些策略
CREATE TABLE `RISK_MODEL_SENCE` (
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键',
  `MODEL_PROCDEF_ID` varchar(64) NOT NULL COMMENT  '模型定义ID',
  `SENCE_VERSION_ID` varchar(64) NOT NULL COMMENT  '決策版本流水号',
  `IS_EFFECT` VARCHAR(2) NOT NULL DEFAULT '0' COMMENT '是否生效：0-有效，1-无效',
  `CREATE_TIME` DATETIME NOT NULL COMMENT  '创建时间',
  `CREATE_USER` VARCHAR(64) COMMENT '创建用户'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


-- 2 模型版本发布审核信息
CREATE TABLE RISK_MODEL_RELEASE(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键',
  `MODEL_PROCDEF_ID` varchar(64) NOT NULL COMMENT  '模型定义ID，与 ACT_RE_PROCDEF.ID_ 关联',
  `MODEL_NAME` varchar(255) COMMENT '模型名称',
  `MODEL_VERSION` varchar(64) COMMENT '模型版本',
  `MODEL_CATEGORY` varchar(64) COMMENT '模型分类',
  `VERSION_TYPE` VARCHAR(2) COMMENT '版本类型，0-测试版，1-正式版',
  `IS_VALIDATE` CHAR NOT NULL DEFAULT '0' COMMENT  '是否验证通过： 0-待验证，1-验证通过，2-验证不通过；默认为0;',
  `IS_APPROVE` CHAR NOT NULL DEFAULT '0' COMMENT '是否审核通过：0-待审核，1-审核通过，2-审核不通过；默认为0;',
  `IS_EFFECT` VARCHAR(2) NOT NULL DEFAULT '0' COMMENT '是否生效：0-有效，1-无效',
  `UPDATE_TIME` DATETIME COMMENT '更新时间',
  `UPDATE_USER` VARCHAR(64) COMMENT '更新用户',
  `CREATE_TIME` DATETIME NOT NULL COMMENT  '创建时间',
  `CREATE_USER` VARCHAR(64) COMMENT '创建用户'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 3模型运行日志表
CREATE TABLE RISK_MODEL_LOG(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键,流程运行ID',
  `RELEASE_ID` varchar(64) NOT NULL COMMENT  '模型发布流水号',
  `CALLTYPE` VARCHAR(8) NOT NULL COMMENT '调用方式；0 数据传入调用、1 通过变量绑定数据库信息获取数据',
  `IN_PARAMTER` BLOB COMMENT '入参',
  `OUT_PARAMTER` BLOB COMMENT '出参',
  `CREATE_TIME` DATETIME NOT NULL COMMENT  '创建时间',
  `CREATE_USER` VARCHAR(64) COMMENT '创建用户'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 4决策执行日志
CREATE TABLE `RISK_DROOLS_LOG` (
  `ID` bigint(20) NOT NULL,
  `PROCINST_ID` bigint(20) DEFAULT NULL COMMENT '模型实例id',
  `MODEL_NAME` varchar(100) DEFAULT NULL COMMENT '模型名',
  `SENCE_VERSIONID` varchar(64) NOT NULL COMMENT  '決策版本流水',
  `IN_PARAMTER` LONGTEXT COMMENT '入参',
  `OUT_PARAMTER` LONGTEXT COMMENT '计算结果',
  `EXECUTE_TOTAL` int(11) DEFAULT NULL COMMENT '命中规则总数',
  `TYPE` VARCHAR(2) DEFAULT NULL COMMENT '决策执行类型：0-直接调用，1-模型调用',
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 5决策执行日志细节
CREATE TABLE `RISK_DROOLS_DETAIL_LOG` (
  `ID` bigint(20) NOT NULL,
  `DROOLS_LOGID` bigint(20) NOT NULL,
  `EXECUTE_RULENAME` varchar(100) DEFAULT NULL COMMENT '命中的规则',
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 6模型验证任务表
CREATE TABLE RISK_VALIDATE_BATCH(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键,批次号',
  `DEPLOYMEN_TID` varchar(64) NOT NULL COMMENT  '流程部署ID，与 ACT_RE_PROCDEF.DEPLOYMENT_ID 关联',
  `BATCH_SIZE` INT(12) NOT NULL  COMMENT  '批次大小',
  `IS_EFFECT` VARCHAR(2) NOT NULL DEFAULT '0' COMMENT '是否生效：0-有效，1-无效',
  `CREATE_TIME` DATETIME NOT NULL COMMENT  '创建时间',
  `CREATE_USER` VARCHAR(64) COMMENT '创建用户'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 7策略变量绑定
CREATE TABLE RISK_VARIABLE_BIND(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键,流水号',
  `SENCE_VERSIONID` varchar(64) NOT NULL COMMENT  '決策版本流水',
  `VARIABLE_CODE` VARCHAR(64) NOT NULL COMMENT '变量编码',
  `VARIABLE_NAME` VARCHAR(64) COMMENT '变量名称',
  `BIND_TABLE` VARCHAR(64) NOT NULL COMMENT '绑定数据表',
  `BIND_COLUMN` VARCHAR(64) NOT NULL COMMENT '绑定数据表字段',
  `IS_EFFECT` VARCHAR(2) NOT NULL DEFAULT '0' COMMENT '是否生效：0-有效，1-无效',
  `CREATE_USER` VARCHAR(64) COMMENT '创建用户',
  `CREATE_TIME` DATETIME NOT NULL COMMENT  '创建时间'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 8模型验证日志
CREATE TABLE RISK_MODEL_VALIDATE_LOG(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键,流程运行ID',
  `BATCH_ID` varchar(64) NOT NULL COMMENT  '任务表，批次号ID',
  `DEPLOYMEN_TID` varchar(64) NOT NULL COMMENT  '流程部署ID，与 ACT_RE_PROCDEF.DEPLOYMENT_ID 关联',
  `IN_PARAMTER` BLOB COMMENT '入参',
  `OUT_PARAMTER` BLOB COMMENT '出参',
  `CREATE_TIME` DATETIME NOT NULL COMMENT  '创建时间',
  `CREATE_USER` VARCHAR(64) COMMENT '创建用户'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 11 规则描述
CREATE TABLE RISK_RULE_HIS_VERSION(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键',
  `SENCE_VERSIONID` varchar(64) NOT NULL COMMENT  '決策版本流水',
  `RULE_NAME` varchar(64) NOT NULL COMMENT  '规则名称',
  `RULE_DESC` varchar(64) NOT NULL COMMENT  '规则描述',
  `IS_EFFECT` VARCHAR(2) NOT NULL DEFAULT '0' COMMENT '是否生效：0-有效，1-无效',
  `CREATE_USER` varchar(64) COMMENT  '创建用户',
  `CREATE_TIME` DATETIME COMMENT  '创建时间'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


-- 还需进一步确定
-- 9模型验证报告信息表
CREATE TABLE RISK_MODEL_REPORT(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键',
  `MODEL_NAME` varchar(64) NOT NULL PRIMARY KEY COMMENT  '模型名称',
  `MODEl_PROCDEFID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '模型定义ID',
  `MODEL_VERSION` varchar(64) NOT NULL PRIMARY KEY COMMENT  '模型版本',
  `RUNNING_TIME` varchar(64) NOT NULL PRIMARY KEY COMMENT  '运行花费时间',
  `SUCCESS_RATE` varchar(64) NOT NULL PRIMARY KEY COMMENT  '成功率',
  `PASS_RATE` varchar(64) NOT NULL PRIMARY KEY COMMENT  '通过率',
  `RUN_TIMES` varchar(64) NOT NULL PRIMARY KEY COMMENT  '运行次数',
  `CREATE_USER` varchar(64) NOT NULL PRIMARY KEY COMMENT  '创建用户',
  `CREATE_TIME` varchar(64) NOT NULL PRIMARY KEY COMMENT  '创建时间'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 10决策验证报告信息表
CREATE TABLE RISK_SENCE_REPORT(
  `ID` varchar(64) NOT NULL PRIMARY KEY COMMENT  '主键',
  `SENCE_CODE` varchar(64) NOT NULL COMMENT  '決策编码',
  `SENCE_NAME` varchar(64) NOT NULL COMMENT  '决策名称',
  `SENCE_VERSION` varchar(64) NOT NULL COMMENT  '决策版本',
  `IS_SUCCESS` char NOT NULL COMMENT  '是否成功',
  `HIT_RATE` DECIMAL(4,4) NOT NULL  COMMENT  '规则命中概率',
  `HITCOUNT_RATE` DECIMAL(4,4) NOT NULL COMMENT  '命中次数概率',
  `CREATE_USER` varchar(64) COMMENT  '创建用户',
  `CREATE_TIME` DATETIME COMMENT  '创建时间'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



