logging:
    level:
        tk.mybatis: DEBUG
        com.github.wxiaoqi.security.admin: DEBUG
  #  config: classpath:logback.xml
    path: /admin-service
server:
    port: 8772

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: admin-service
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF8
        username: root
        password: zhangzhen
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    basepackage: com.ht.risk.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml



