spring:
    application:
        name: risk-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    profiles:
      active: dev
server:
    port: 30501

eureka:
    client:
        serviceUrl:
            defaultZone:  http://10.110.1.240:10001/eureka/

