spring:
    application:
        name: risk-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

server:
    port: 8766

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
