
#配置日志
#logging.level.com.tdw.cams.account.mapper=debug
logging:
    level:
        #tk.mybatis: DEBUG
        #com.github.wxiaoqi.security.admin: DEBUG
        com.ht.risk.rule.mapper:DEBUG
  #  config: classpath:logback.xml
    path: /risk-admin

spring:
    application:
        name: risk-admin
    boot:
        admin:
             url: http://localhost:8764
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/drools_rule?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ht.risk.rule.entity
  typeEnumsPackage: com.ht.risk.rule.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
   # meta-object-handler: com.zp.plus.util.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

server:
    port: 8762

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
swagger:
      basepackage: com.ht.risk.rule.controller
      service:
            name:risk-rule-service
            description:risk-rule-service
            developer=F1